version: "2"

services:

  ############################################ Service ############################################
  nats:
    image: 'nats:1.3.0'
    entrypoint: "/gnatsd -DV --http_port 8222"
    expose:
      - "4222"
      - "8222"
    labels:
      - "traefik.enable=false"
  redis:
    image: 'redis:5.0.3'
    ports:
      - "6379:6379"
    expose:
      - "6379"
    labels:
      - "traefik.enable=false"
  mysql:
    image: 'mysql:8.0.13'
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=my-secret-pw"
      - "MYSQL_DATABASE=cqrs"
      - "MYSQL_USER=cqrsuser"
      - "MYSQL_PASSWORD=cqrspassword"
    labels:
      - "traefik.enable=false"
  
  ############################################ API Gateway ############################################
  kong-database:
    image: postgres:9.5
    environment:
      - "POSTGRES_USER=kong"
      - "POSTGRES_DB=kong"
    labels:
      - "traefik.enable=false"
  kong-init:
    image: cqrs/kong-init:latest
    links:
      - kong-database
      - loadbalancer
    environment:
      - "KONG_DATABASE=postgres"
      - "KONG_PG_HOST=kong-database"
      - "KONG_PROXY_ACCESS_LOG=/dev/stdout"
      - "KONG_ADMIN_ACCESS_LOG=/dev/stdout"
      - "KONG_PROXY_ERROR_LOG=/dev/stderr"
      - "KONG_ADMIN_ERROR_LOG=/dev/stderr"
      - "KONG_ADMIN_LISTEN=0.0.0.0:8001"
    depends_on:
      - kong-database
    ports:
      - "8000:8000"
      - "8001:8001"
    labels:
      - "traefik.enable=false"
  loadbalancer:
    image: traefik:1.7.6
    command: 
      - --api 
      - --docker
      - "--entryPoints=Name:read Address::8081 Compress:true"
      - "--entryPoints=Name:write Address::8082 Compress:true"
    ports:
      - "80"        # The HTTP port
      - "8080:8080" # The Web UI (enabled by --api)
    expose:
      - "80"
      - "8081"
      - "8082"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
    labels:
      - "traefik.enable=false"

  ############################################ Apps ############################################
  write:
    image: 'cqrs/write-ws:latest'
    links:
      - nats
      - mysql
    environment:
      - "NATS_URI=nats://nats:4222"
      - "MYSQL_USER=cqrsuser"
      - "MYSQL_PASSWORD=cqrspassword"
      - "MYSQL_HOST=mysql"
      - "MYSQL_NAME=cqrs"
    depends_on:
      - nats
      - mysql
    expose:
      - "8080"
    labels:
      - "traefik.frontend.entryPoints=write"
      - "traefik.frontend.rule=Host:loadbalancer"
  read:
    image: 'cqrs/read-ws:latest'
    links:
      - redis
    environment:
      - "NATS_URI=nats://nats:4222"
      - "REDIS_URI=redis:6379"
    depends_on:
      - nats
    expose:
      - "8080"
    labels:
      - "traefik.frontend.entryPoints=read"
      - "traefik.frontend.rule=Host:loadbalancer"
  convert:
    image: 'cqrs/convert-ws:latest'
    links:
      - redis
      - nats
    environment:
      - "REDIS_URI=redis:6379"
      - "NATS_URI=nats://nats:4222"
    depends_on:
      - nats
    expose:
      - "8080"
    labels:
      - "traefik.enable=false"