version: "2"

services:
  nats:
    image: 'nats:1.3.0'
    entrypoint: "/gnatsd -DV --http_port 8222"
    expose:
      - "4222"
      - "8222"
  redis:
    image: 'redis:5.0.3'
    expose:
      - "6379"
  mysql:
    image: 'mysql:8.0.13'
    expose:
      - "3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=my-secret-pw"
      - "MYSQL_DATABASE=cqrs"
      - "MYSQL_USER=cqrsuser"
      - "MYSQL_PASSWORD=cqrspassword"
  kong-database:
    image: postgres:9.5
    environment:
      - "POSTGRES_USER=kong"
      - "POSTGRES_DB=kong"
  # kong-init:
  #   image: kong:0.14
  #   command: kong migrations up
  #   links:
  #     - kong-database
  #   environment:
  #     - "KONG_DATABASE=postgres"
  #     - "KONG_PG_HOST=kong-database"
  #   depends_on:
  #     - kong-database
  # kong:
  #   image: kong:0.14
  #   links:
  #     - kong-database
  #   environment:
  #     - "KONG_DATABASE=postgres"
  #     - "KONG_PG_HOST=kong-database"
  #     - "KONG_LOG_LEVEL=info"
  #     - "KONG_ADMIN_LISTEN=0.0.0.0:8001"
  #   ports:
  #     - "8000:8000"
  #     - "8001:8001"
  #   depends_on:
  #     - kong-database

  write:
    image: 'cqrs/write-ws:latest'
    links:
      - nats
      - mysql
    environment:
      - "NATS_URI=nats://nats:4222"
      - "MYSQL_USER=cqrsuser"
      - "MYSQL_PASSWORD=cqrspassword"
      - "MYSQL_HOST=mysql"
      - "MYSQL_NAME=cqrs"
    depends_on:
      - nats
      - mysql
    expose:
      - "8080"
  read:
    image: 'cqrs/read-ws:latest'
    links:
      - redis
    environment:
      - "NATS_URI=nats://nats:4222"
      - "REDIS_URI=redis:6379"
    depends_on:
      - nats
    expose:
      - "8080"
  convert:
    image: 'cqrs/convert-ws:latest'
    links:
      - redis
      - nats
    environment:
      - "REDIS_URI=redis:6379"
      - "NATS_URI=nats://nats:4222"
    depends_on:
      - nats
    expose:
      - "8080"