global:
  scrape_interval: 15s

scrape_configs:
  - job_name: traefik
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['loadbalancer:8083']
  - job_name: read
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['read:8080']
  - job_name: write
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['write:8080']
  - job_name: convert
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['convert:8080']
